import { Poppins } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Al-Ansari Associates",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased max-w-[1920px] mx-auto`}>
        <NextTopLoader
          color="#AF8B18"
          height={2}
          showSpinner={false}
        />
        {children}
      </body>
    </html>
  );
}

