import "./globals.css";
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import NextTopLoader from 'nextjs-toploader';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Al-Ansari Associates",
  description: "Generated by create next app",
};
export default async function Locallayout({ children, params }) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={`${poppins.variable} antialiased max-w-[1920px] mx-auto`}>
         <NextTopLoader
          color="#AF8B18"
          height={2}
          showSpinner={false}
        />
        <NextIntlClientProvider>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}